[package]
name = "common-types"
authors = ["Grafbase"]
description = "Various type definitions for the Grafbase platform"
version = "0.1.0"
edition = "2021"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["types", "grafbase"]

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum = { workspace = true, features = ["derive"] }
