[package]
name = "parser-postgres"
description = "Grafbase schema introspection for Postgres database"
version = "0.1.0"
edition = "2021"
authors = ["Grafbase"]
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "parser", "postgres", "grafbase"]

[lints]
workspace = true

[dependencies]
parser-sdl = { path = "../parser-sdl" }
postgres-connector-types = { path = "../postgres-connector-types" }
serde_json.workspace = true
serde.workspace = true
registry-v1.workspace = true
registry-v2.workspace = true
indoc = "2"
Inflector = "0.11.4"
itertools.workspace = true
common-types.workspace = true
indexmap.workspace = true
grafbase-workspace-hack.workspace = true
