[package]
name = "graphql-schema-validation"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0"
description = "A spec compliant implementation of GraphQL SDL schema validation"
repository = "https://github.com/grafbase/grafbase/tree/main/engine/crates/validation"
keywords = ["graphql"]

[lints]
workspace = true

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
miette = { version = "7.2.0" }
bitflags.workspace = true
grafbase-workspace-hack.workspace = true

[dev-dependencies]
datatest-stable = "0.2.9"
similar = "2.5.0"
miette = { version = "7.2.0", features = ["fancy"] }

[[test]]
name = "validation_tests"
harness = false
