[toolchain]
channel = "1.74"
targets = [
    "x86_64-unknown-linux-musl",  # Tools
    "aarch64-unknown-linux-musl", # AWS Lambda
    "wasm32-unknown-unknown",     # Cloudflare Workers
]
components = ["rustfmt", "clippy"]
profile = "minimal"
