[package]
name = "response-hooks"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
grafbase-hooks.workspace = true
postcard = { version = "1.0.10", features = ["use-std"] }
serde.workspace = true
serde_json.workspace = true

[lib]
crate-type = ["cdylib"]
