[package]
name = "grafbase"
description = "The Grafbase command line interface"
categories = ["command-line-utilities"]
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
backtrace = "0.3"
clap = { version = "4", features = ["cargo", "wrap_help", "derive"] }
clap_complete = "4"
colored = "2"
ctrlc = "3"
indicatif = "0.17"
inquire = "0.6"
exitcode = "1"
hex-literal = "0.4"
indoc = "2"
itertools = "0.11"
log = "0.4"
once_cell = "1"
os_type = "2"
serde = "1"
serde_derive = "1"
serde_json = { version = "1", features = ["preserve_order"] }
slugify = "0.1.0"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ulid = "1"
uuid = { version = "1", features = ["v4"] }
url = "2"
webbrowser = "0.8"

backend = { package = "grafbase-local-backend", path = "../backend", version = "0.36.0-rc.3" }
common = { package = "grafbase-local-common", path = "../common", version = "0.36.0-rc.3" }


[dev-dependencies]
async-graphql = "5"
async-graphql-axum = "5"
async-trait = "0.1"
axum = "0.6"
cfg-if = "1"
chrono = "0.4"
cynic = "3"
cynic-introspection = "3"
derive_builder = "0.12"
dirs = "5"
duct = "0.13"
fslock = "0.2"
futures-util = "0.3"
insta = { version = "1.31", features = ["json", "redactions", "yaml"] }
json_dotpath = "1"
jwt-compact = { version = "0.8.0-beta.1", default-features = false, features = [
  "clock",
  "rsa",
] }
multipart-stream = { git = "https://github.com/grafbase/multipart-stream-rs.git", branch = "fix-multipart-mixed" }
rand = "0.8"
reqwest = { version = "0.11", features = [
  "rustls-tls",
  "json",
  "blocking",
], default-features = false }
rsa = "0.9"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.29"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
url = "2"
regex = "1"
reqwest-eventsource = "0.4"
rstest = "0.18"
rusoto_core = "0.48"
rusoto_dynamodb = "0.48"
strum = { version = "0.25", features = ["derive"] }
which = "4"
wiremock = "0.5"

[[bin]]
name = "grafbase"

[features]
dynamodb = ["backend/dynamodb"]
