[package]
name = "grafbase"
version = "0.18.7"
edition = "2021"
description = "The Grafbase command line interface"
license = "Apache-2.0"
homepage = "https://grafbase.com"
keywords = ["grafbase"]
readme = "README.md"
repository = "https://github.com/grafbase/grafbase"
categories = ["command-line-utilities"]

[dependencies]
backtrace = "0.3"
cfg-if = "1"
clap = { version = "4", features = ["cargo", "wrap_help"] }
clap_complete = "4"
colored = "2"
ctrlc = "3"
fslock = "0.2"
indicatif = "0.17"
inquire = "0.6"
exitcode = "1"
hex-literal = "0.3"
humantime = "2"
indoc = "2"
log = "0.4"
once_cell = "1"
os_type = "2"
serde = "1"
serde_derive = "1"
slugify = "0.1.0"
thiserror = "1"
toml = "0.7"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
webbrowser = "0.8"

backend = { package = "grafbase-local-backend", path = "../backend", version = "0.18.7" }
common = { package = "grafbase-local-common", path = "../common", version = "0.18.7" }
server = { package = "grafbase-local-server", path = "../server", version = "0.18.6" }

[dev-dependencies]
chrono = "0.4"
crossbeam-channel = "0.5"
duct = "0.13"
insta = { version = "1.28", features = ["json", "redactions", "yaml"] }
json_dotpath = "1"
jwt-compact = { version = "0.6", default-features = false, features = [
  "clock",
] }
rand = "0.8"
reqwest = { version = "0.11", features = [
  "rustls-tls",
  "json",
  "blocking",
], default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.28"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
regex = "1"
rstest = "0.17"
wiremock = "0.5"

[[bin]]
name = "grafbase"
