[package]
name = "grafbase"
description = "The Grafbase command line interface"
categories = ["command-line-utilities"]
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
assert_matches = "1.5.0"
backtrace = "0.3.71"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["cargo", "wrap_help", "derive", "env"] }
clap_complete = "4.5.2"
colored = "2.1.0"
ctrlc = "3.4.4"
dirs = "5.0.1"
exitcode = "1.1.2"
futures-util = "0.3.30"
fslock = "0.2.1"
indicatif = "0.17.8"
indoc = "2.0.5"
inquire = "0.7.5"
itertools.workspace = true
log = "0.4.21"
lru = "0.12.3"
mimalloc = "0.1.41"
once_cell = "1.19.0"
os_type = "2.6.0"
reqwest = { workspace = true, features = [
  "rustls-tls",
  "stream",
  "json",
], default-features = false }
rustls = { workspace = true, features = ["ring", "tls12"] }
serde = "1.0.199"
serde_derive = "1.0.199"
serde_json.workspace = true
slugify = "0.1.0"
strum = { version = "0.26.2", features = ["derive"] }
syntect = "5.2.0"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["futures-io", "compat"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
ulid = "1.1.2"
url = "2.5.0"
uuid = { version = "1.8.0", features = ["v4"] }
webbrowser = "1.0"

backend = { package = "grafbase-local-backend", path = "../backend", version = "0.79.2" }
common = { package = "grafbase-local-common", path = "../common", version = "0.79.2" }
federated-dev = { path = "../federated-dev" }
grafbase-graphql-introspection.workspace = true
graphql-lint.workspace = true
graph-ref = { path = "../../../graph-ref" }
server = { package = "grafbase-local-server", path = "../server", version = "0.79.2" }
prettytable = { version = "0.10.0", default-features = false, features = ["win_crlf"] }

[dev-dependencies]
async-graphql-axum.workspace = true
async-graphql.workspace = true
async-trait = "0.1.80"
async-tungstenite = "0.26.0"
axum.workspace = true
cfg-if = "1"
chrono = "0.4.38"
ctor.workspace = true
cynic-introspection.workspace = true
cynic.workspace = true
derive_builder = "0.20"
dirs = "5.0.1"
duct = "0.13.7"
fslock = "0.2.1"
futures-util = "0.3.30"
graphql-mocks.workspace = true
graphql-ws-client = { version = "0.10.0", features = ["tungstenite"] }
headers.workspace = true
hex.workspace = true
http.workspace = true
insta = { workspace = true, features = ["json", "redactions", "yaml"] }
json_dotpath = "1.1.0"
jwt-compact = { version = "0.8.0", default-features = false, features = [
  "clock",
  "rsa",
] }
more-asserts = "0.3.1"
multipart-stream = "0.1.2"
rand = "0.8.5"
regex = "1.10.4"
reqwest = { workspace = true, features = [
  "rustls-tls",
  "json",
] }
reqwest-eventsource = "0.6"
rsa = "0.9.6"
rstest = "0.21"
rstest_reuse = "0.7"
serde = { version = "1.0.199", features = ["derive"] }
sha2.workspace =true
strum = { version = "0.26.2", features = ["derive"] }
sysinfo = "0.30.11"
tempfile = "3.10.1"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = "0.5.2"
url = "2.5.0"
which.workspace = true
wiremock.workspace = true

[[bin]]
name = "grafbase"

[features]
default = []

[lints]
workspace = true
