[package]
name = "grafbase"
description = "The Grafbase command line interface"
categories = ["command-line-utilities"]
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
assert_matches = "1"
backtrace = "0.3"
chrono = "0.4"
clap = { version = "4", features = ["cargo", "wrap_help", "derive"] }
clap_complete = "4"
colored = "2"
ctrlc = "3"
indicatif = "0.17"
inquire = "0.6"
exitcode = "1"
indoc = "2"
itertools.workspace = true
log = "0.4"
once_cell = "1"
os_type = "2"
serde = "1"
serde_derive = "1"
serde_json.workspace = true
slugify = "0.1.0"
strum = { version = "0.26", features = ["derive"] }
syntect = "5"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ulid = "1"
uuid = { version = "1", features = ["v4"] }
url = "2"
webbrowser = "0.8"
lru = "0.12"
futures-util = "0.3"
mimalloc = "0.1"

atty = "0.2"
backend = { package = "grafbase-local-backend", path = "../backend", version = "0.55.0" }
common = { package = "grafbase-local-common", path = "../common", version = "0.55.0" }
federated-dev = { path = "../federated-dev" }
graphql-introspection = { package = "grafbase-graphql-introspection", path = "../graphql-introspection" }
server = { package = "grafbase-local-server", path = "../server", version = "0.55.0" }

[dev-dependencies]
async-graphql-axum.workspace = true
async-graphql.workspace = true
async-trait = "0.1"
async-tungstenite = "0.24"
axum.workspace = true
cfg-if = "1"
chrono = "0.4"
cynic.workspace = true
cynic-introspection.workspace = true
derive_builder = "0.13"
dirs = "5"
duct = "0.13"
fslock = "0.2"
futures-util = "0.3"
graphql-mocks.workspace = true
graphql-ws-client = "0.7"
http.workspace = true
headers.workspace = true
insta = { version = "1.34", features = ["json", "redactions", "yaml"] }
json_dotpath = "1"
jwt-compact = { version = "0.8.0", default-features = false, features = [
  "clock",
  "rsa",
] }
multipart-stream = "0.1"
rand = "0.8"
regex = "1"
reqwest = { workspace = true, features = [
  "rustls-tls",
  "json",
], default-features = false }
reqwest-eventsource = "0.5"
rsa = "0.9"
rstest = "0.18"
rstest_reuse = "0.6"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
sysinfo = "0.30"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
url = "2"
which = "6"
wiremock.workspace = true

[[bin]]
name = "grafbase"

[features]
default = []

[lints]
workspace = true
