[package]
name = "engine-value"
authors = ["Grafbase"]
description = "A GraphQL value type for engine"
version = "3.0.31"
edition = "2021"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "value", "grafbase"]

[features]
default = []

[dependencies]
serde_json.workspace = true
serde.workspace = true
bytes = { version = "1.6.0", features = ["serde"] }
indexmap = { workspace = true, features = ["serde"] }
grafbase-workspace-hack = { version = "0.1", path = "../../../../workspace-hack" }
