[package]
name = "users-subgraph"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-graphql = "7"
async-graphql-axum = "7"
axum = "0.7"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }

