[package]
name = "partial-caching"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
common-types.workspace = true
cynic-parser = { workspace = true, features = ["print"] }
engine-value.workspace = true
graph-entities.workspace = true
headers.workspace = true
http.workspace = true
indexmap.workspace = true
internment = "0.8"
query-path.workspace = true
registry-for-cache.workspace = true
runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
grafbase-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[dev-dependencies]
insta.workspace = true
parser-sdl.workspace = true
registry-upgrade.workspace = true

[lints]
workspace = true
