[package]
name = "hooks"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
postcard = { version = "1.0.10", features = ["use-std"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
wit-bindgen-rt = { version = "0.32.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:demo-hooks"
