[package]
name = "rest"
version = "0.1.3"
edition = "2021"
license = "MPL-2"
homepage = "https://grafbase.com"
keywords = ["graphql"]
repository = "https://github.com/grafbase/grafbase"

[dependencies]
grafbase-sdk = { path = "../../crates/grafbase-sdk" }
jaq-interpret = "1.5.0"
jaq-parse = "1.0.3"
serde = "1"
serde_json = "1"
http = "1"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
