[package]
name = "parser-sdl"
authors = ["Grafbase"]
description = "A parser that transforms GraphQL SDL into the Grafbase registry format"
version = "0.1.0"
edition = "2021"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["parser", "sdl", "grafbase"]

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
case = "1"
colored = "2.1.0"
common-types.workspace = true
duration-str = "0.8"
engine = { path = "../engine" }
engine-parser = { path = "../engine/parser" }
engine-value.workspace = true
futures = "0.3"
if_chain = "1"
indexmap.workspace = true
Inflector = { version = "0.11", default-features = false }
itertools.workspace = true
nom = "7"
regex.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tuple = "0.5"
url = { version = "2" }

[dev-dependencies]
assert_matches = "1"
indoc = "2.0.5"
insta.workspace = true
maplit = "1"
pretty_assertions = "1"
rstest.workspace = true

[features]
default = []
local = []
