[package]
name = "gateway"
description = "Grafbase gateway executing the engine for local use with axum"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
async-graphql.workspace = true
async-trait = "0.1"
axum.workspace = true
bytes = "1"
futures-util.workspace = true
http.workspace = true
serde_json = "1"
thiserror = "1"
tokio.workspace = true
tower-http = { workspace = true, features = ["cors"] }
ulid = "1"
# hyper = "0.14"

engine = { path = "../../../engine/crates/engine" }
graphql-extensions = { path = "../../../engine/crates/graphql-extensions", features = [
  "local",
] }
gateway-core = { path = "../../../engine/crates/gateway-core" }
runtime = { path = "../../../engine/crates/runtime" }
runtime-local = { path = "../../../engine/crates/runtime-local" }
runtime-noop = { path = "../../../engine/crates/runtime-noop" }
common-types = { path = "../../../engine/crates/common-types" }
postgres-connector-types = { path = "../../../engine/crates/postgres-connector-types" }

[features]
default = []

[lints]
workspace = true
