[package]
name = "gateway"
description = "Grafbase gateway executing the engine for local use with axum"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
async-graphql = "6"
async-trait = "0.1"
axum = { workspace = true }
futures-util = { workspace = true }
thiserror = "1"
http = "0.2"
tokio = { workspace = true }
rusoto_core = "0.48"
bytes = "1"
serde_json = "1"
tower-http = { version = "0.4", features = ["cors"] }
ulid = "1"
# hyper = "0.14"

engine = { path = "../../../engine/crates/engine" }
dynamodb = { path = "../../../engine/crates/dynamodb", features = ["local"] }
graphql-extensions = { path = "../../../engine/crates/graphql-extensions", features = [
  "local",
] }
gateway-core = { path = "../../../engine/crates/gateway-core" }
runtime = { path = "../../../engine/crates/runtime" }
runtime-local = { path = "../../../engine/crates/runtime-local" }
runtime-noop = { path = "../../../engine/crates/runtime-noop" }
common-types = { path = "../../../engine/crates/common-types" }
log = { path = "../../../engine/crates/log", features = ["local"] }

[features]
default = ["sqlite"]
sqlite = ["dynamodb/sqlite"]
dynamodb = []
