[package]
name = "parser-graphql"
authors = ["Grafbase"]
description = "A GraphQL schema parser for upstream APIs connected to Grafbase"
version = "0.1.0"
edition = "2021"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "parser", "grafbase"]

[lints]
workspace = true

[dependencies]
engine.workspace = true
engine-parser.workspace = true
registry-v2.workspace = true

serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

cynic = { workspace = true, features = ["http-reqwest"] }
cynic-introspection.workspace = true
http.workspace = true
Inflector = { version = "0.11.4", default-features = false }
grafbase-workspace-hack.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true, features = [
  "json",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true, features = [
  "json",
  "rustls-tls",
] }

[dev-dependencies]
ctor.workspace = true
rustls = { workspace = true, features = ["ring"] }
insta.workspace = true
tokio = { workspace = true, features = ["macros"] }
wiremock.workspace = true
graphql-schema-validation = { path = "../validation" }

