[package]
name = "hooks-template"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
homepage = "https://grafbase.com"
keywords = ["grafbase"]
repository = "https://github.com/grafbase/grafbase"

[dependencies]
grafbase-hooks = "0.1.8"

[lib]
crate-type = ["cdylib"]

[package.metadata.component.dependencies]
