[package]
name = "graphql-schema-diff"
description = "Semantic diffing for GraphQL schemas"
version = "0.2.0"
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
keywords = ["graphql"]
repository = "https://github.com/grafbase/grafbase/tree/main/engine/crates/graphql-schema-diff"

[dependencies]
cynic-parser.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
grafbase-workspace-hack.workspace = true

[features]
default = ["serde"]

[lints]
workspace = true

[dev-dependencies]
datatest-stable = "0.2.9"
similar = "2.5.0"
miette = { version = "7.2.0", features = ["fancy"] }
serde_json.workspace = true

[[test]]
name = "diff_tests"
harness = false

[[test]]
name = "patch_tests"
harness = false
