[package]
name = "graphql-schema-diff"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
async-graphql-parser.workspace = true
async-graphql-value.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }

[features]
default = ["serde"]

[lints]
workspace = true

[dev-dependencies]
datatest-stable = "0.2.3"
similar = "2"
miette = { version = "5.10.0", features = ["fancy"] }
serde_json.workspace = true

[[test]]
name = "diff_tests"
harness = false
