[package]
name = "postgres-connector-types"
description = "Shared types for Postgres connector"
version = "0.1.0"
edition = "2021"
authors = ["Grafbase"]
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "postgres", "grafbase"]

[lints]
workspace = true

[dependencies]
Inflector = "0.11.4"
async-trait = "0.1.80"
async-stream = "0.3.5"
async-runtime.workspace = true
flexbuffers.workspace = true
futures.workspace = true
indexmap = { workspace = true, features = ["serde"] }
itertools.workspace = true
graphql-cursor.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true
tracing.workspace = true
grafbase-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[features]
pooling = ["deadpool-postgres"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true, features = ["json"] }
# https://github.com/sfackler/rust-postgres/pull/1067
tokio-postgres = { workspace = true, features = ["js"] }
worker.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
rustls.workspace = true
rustls-native-certs = "0.7.0"
# https://github.com/sfackler/rust-postgres/pull/1067
tokio-postgres = { workspace = true, features = ["runtime"] }
tokio-postgres-rustls.workspace = true
deadpool-postgres = { workspace = true, optional = true }
