[package]
name = "engine-id-newtypes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
common-types.workspace = true
engine-value.workspace = true
gateway-v2-auth-config.workspace = true
indexmap.workspace = true
postgres-connector-types.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
url.workspace = true
grafbase-workspace-hack = { version = "0.1", path = "../../../../workspace-hack" }
