[package]
name = "registry-v2-generator"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
indexmap = "2.2.6"
indoc = "2.0.5"
itertools = "0.13.0"
proc-macro2 = "1.0.81"
quote = "1.0.36"
xshell = "0.2.6"

cynic-parser.workspace = true

cynic-parser.features = ["report"]
grafbase-workspace-hack.workspace = true
