[package]
name = "graphql-extensions"
authors = ["Grafbase"]
description = "Contains extensions for grafbase-engine"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["extensions", "graphql", "grafbase"]

[dependencies]
async-trait = "0.1"
lazy_static = "1"
web-time = { workspace = true }

grafbase-engine = { path = "../grafbase-engine", default-features = false }
grafbase-engine-value = { workspace = true }
log = { path = "../log", features = ["with-worker"] }
runtime = { workspace = true }
common-types = { workspace = true }

[features]
local = []
