[package]
name = "jwt-verifier"
version = "0.1.0"
description = "Verify JSON Web Tokens"
edition = "2021"

[lints]
workspace = true

[dependencies]
futures-util.workspace = true
json_dotpath = "1.1.0"
jwt-compact = { version = "0.8", features = ["clock", "rsa"] }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror = "1.0.59"
url = { workspace = true, features = ["serde"] }
runtime.workspace = true
tracing.workspace = true
grafbase-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true, features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { workspace = true, features = [
  "json",
  "rustls-tls",
] }

[dev-dependencies]
chrono = "0.4.38"
serde_json.workspace = true
tokio = { version = "1.37.0", features = ["macros"] }
wiremock.workspace = true
ctor.workspace = true
rustls = { workspace = true, features = ["ring"] }
