[package]
name = "postgresql-types"
description = "Shared types for PostgreSQL connector"
version = "0.1.0"
edition = "2021"
authors = ["Grafbase"]
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "postgresql", "grafbase"]

[dependencies]
Inflector = "0.11.4"
async-trait = "0.1.73"
indexmap = { version = "1", features = ["serde"] }
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
