[package]
name = "engine-derive"
authors = ["Grafbase"]
description = "Macros for engine"
version = "3.0.31"
edition = "2021"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["macros", "engine", "grafbase"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = [
    "full",
    "extra-traits",
    "visit-mut",
    "visit",
] }
quote = "1"
Inflector = { version = "0.11", default-features = false }
proc-macro-crate = "3"
darling = "0.20"
thiserror.workspace = true
