[package]
name = "graph-entities"
authors = ["Grafbase"]
description = "Various types for use with GraphQL on the Grafbase platform"
version = "0.1.0"
edition = "2021"
publish = false
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "types", "grafbase"]

[lints]
workspace = true

[dependencies]
engine-value = { path = "../engine/value", version = "3" }
internment = { version = "0.7", features = ["serde", "arc"] }
serde_json.workspace = true
serde.workspace = true
thiserror.workspace = true
