[graph]
introspection = true

[subgraphs.locations]
schema_path = "./gen/graphql/locations.graphql"

[subgraphs.parts]
schema_path = "./gen/graphql/parts.graphql"

[subgraphs.products]
schema_path = "./gen/graphql/products.graphql"

[extensions]
grpc.path = "/home/tom/src/gh/grafbase/extensions/extensions/grpc/build"
# grpc.version = "0.2"

[[extensions.grpc.config.services]]
name = "parts.PartService"
address = "http://localhost:50052"

[[extensions.grpc.config.services]]
name = "products.ProductService"
address = "http://localhost:50051"

[[extensions.grpc.config.services]]
name = "locations.LocationService"
address = "http://localhost:50053"
