[package]
name = "runtime"
authors = ["Grafbase"]
description = "An abstraction over the various Grafbase runtime environments"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["runtime", "environment", "grafbase"]

[lints]
workspace = true

[dependencies]
async-runtime = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }
tracing-futures = { workspace = true }

search-protocol = { path = "../search-protocol" }
postgres-connector-types = { path = "../postgres-connector-types" }
common-types = { workspace = true }

[features]
test-utils = []

[dev-dependencies]
tokio = { version = "1.35", features = ["full"]}
