[package]
name = "gateway-core"
version = "3.0.31"
authors = ["Grafbase"]
description = "Grafbase gateway core logic"
edition = "2021"
readme = "README.md"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "gateway", "grafbase"]

[lints]
workspace = true

[dependencies]
async-graphql.workspace = true
async-runtime.workspace = true
async-sse = "5"
async-trait = "0.1"
bytes.workspace = true
common-types.workspace = true
engine.workspace = true
engine-value.workspace = true
futures-util.workspace = true
headers.workspace = true
http.workspace = true
mediatype = "0.19"
mime = "0.3"
multipart-stream = "0.1"
runtime = { workspace = true, features = ["test-utils"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
tracing.workspace = true
gateway-v2-auth = { path = "../gateway-v2/auth" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
engine-value.workspace = true
