[package]
name = "gateway-core"
version = "3.0.31"
authors = ["Grafbase"]
description = "Grafbase gateway core logic"
edition = "2021"
readme = "README.md"
license = "MPL-2.0"
homepage = "https://grafbase.com"
repository = "https://github.com/grafbase/grafbase"
keywords = ["graphql", "gateway", "grafbase"]

[features]
default = []

[lints]
workspace = true

[dependencies]
async-graphql.workspace = true
async-runtime.workspace = true
async-sse.workspace = true
async-trait.workspace = true
bytes.workspace = true
common-types.workspace = true
cynic-parser.workspace = true
engine-parser.workspace = true
engine-validation.workspace = true
engine-value.workspace = true
engine.workspace = true
futures-channel.workspace = true
futures-util.workspace = true
grafbase-telemetry.workspace = true
headers.workspace = true
http.workspace = true
mediatype.workspace = true
mime = "0.3.17"
multipart-stream.workspace = true
operation-normalizer = { path = "../operation-normalizer" }
partial-caching.workspace = true
registry-for-cache.workspace = true
runtime = { workspace = true, features = ["test-utils"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
strum.workspace = true
thiserror.workspace = true
tracing.workspace = true
gateway-v2-auth = { path = "../gateway-v2/auth" }
web-time.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
engine-value.workspace = true
registry-upgrade.workspace = true
