[package]
name = "engine-config-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap.workspace = true

engine-v2-config = { path = "../engine-v2/config" }
federated-graph.workspace = true
parser-sdl.workspace = true
gateway-config.workspace = true
grafbase-workspace-hack.workspace = true

[lints]
workspace = true
