[package]
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license = "MPL-2.0"
name = "gateway-config"
repository.workspace = true
version = "0.13.1"

[lints]
workspace = true

[features]
# historic feature flag used for telemetry config, maybe should be removed?
otlp = ["dep:tonic"]

[dependencies]
chrono.workspace = true
ascii = { version = "1.1.0", features = ["serde"] }
tonic = { workspace = true, optional = true, features = ["tls-roots"] }
duration-str = "0.11.0"
http.workspace = true
regex.workspace = true
serde.workspace = true
serde_with.workspace = true
serde-dynamic-string.workspace = true
serde_regex = "1.1.0"
size = "0.5.0-preview2"
tower-http = { version = "0.5.2", features = ["cors", "timeout"] }
url = { workspace = true, features = ["serde"] }
cfg-if = "1.0.0"
grafbase-workspace-hack.workspace = true

[dev-dependencies]
indoc = "2.0.5"
insta.workspace = true
temp-env = "0.3.6"
toml = "0.8.12"
tempfile = "3.10.1"
