[package]
name = "registry-for-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
engine-id-newtypes.workspace = true
indexmap.workspace = true
registry-v2.workspace = true
serde.workspace = true
serde_json.workspace = true
wrapping.workspace = true
