[graph]
introspection = true

[hooks]
location = "target/wasm32-wasip1/release/hooks.wasm"
stdout = true
stderr = true
environment_variables = true
networking = true

[entity_caching]
enabled = true
ttl = "60s"
