[target.'cfg(all())']
rustflags = [
    "-Dclippy::all",
    "-Dclippy::pedantic",
    "-Dclippy::panic",
    "-Dnonstandard-style",
    "-Drust-2018-idioms",
    "-Dunused-crate-dependencies",
    "-Aclippy::missing-errors-doc",
    "-Aclippy::missing-panics-doc",
    "-Aclippy::module-name-repetitions",
    "-Aclippy::enum_variant_names",
]

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse"
