[package]
name = "grafbase-graphql-introspection"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cynic = { workspace = true, features = ["http-reqwest"] }
cynic-introspection.workspace = true
cynic-parser = { workspace = true, features = ["pretty"] }
grafbase-workspace-hack.workspace = true
indoc.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde.workspace = true
