[package]
name = "grafbase-mcp"
edition.workspace = true
license = "MPL-2.0"
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["macros", "ws", "query", "json"] }
convert_case.workspace = true
engine.workspace = true
engine-operation.workspace = true
engine-schema.workspace = true
fixedbitset.workspace = true
futures.workspace = true
fxhash.workspace = true
gateway-config.workspace = true
grafbase-workspace-hack.workspace = true
http.workspace = true
itertools.workspace = true
minicbor-serde.workspace = true
ordered-float.workspace = true
priority-queue.workspace = true
quick_cache.workspace = true
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tantivy.workspace = true
tokio = { workspace = true, features = ["signal", "time", "net"] }
tokio-stream = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing.workspace = true
unicode-normalization.workspace = true
