name: engine

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-change-type:
    runs-on: buildjet-8vcpu-ubuntu-2204
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Path filter check
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            build:
              - 'cli/**/*'
              - 'engine/**/*'
              - '.github/workflows/engine.yml'
              - '.github/actions/**/*'

  clippy:
    needs: [detect-change-type]
    if: ${{ needs.filter.outputs.build == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: cargo fmt
        shell: bash
        working-directory: engine
        run: cargo fmt --check

      - name: cargo clippy
        shell: bash
        working-directory: engine
        run: cargo clippy --locked --all-targets --tests -- -D warnings

  cargo-integration-tests:
    name: Run Rust integration tests
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start local databases
        run: |
          docker-compose -f engine/crates/integration-tests/docker-compose.yml up -d

      - name: Install cargo-nextest
        run: |
          curl \
            --config ${GITHUB_WORKSPACE}/.github/curl_options \
            https://get.nexte.st/latest/linux \
            | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Test Engine
        working-directory: ./engine/crates/integration-tests
        run: |
          cargo nextest run --profile ci
          exitcode="$?"

  cargo-unit-tests:
    name: Run Rust unit tests
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Install cargo-nextest
        run: |
          curl \
            --config ${GITHUB_WORKSPACE}/.github/curl_options \
            https://get.nexte.st/latest/linux \
            | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - name: Unit Tests
        working-directory: ./engine
        run: |
          cargo nextest run \
            --workspace \
            --exclude integration-tests \
            --profile ci
          exitcode="$?"
