name: Release

defaults:
  run:
    working-directory: cli

on:
  workflow_call:
    inputs:
      draft:
        type: boolean
        required: true
      tag:
        type: string
        required: true
    secrets:
      CRATES_ACCESS_TOKEN:
        required: true
      NPM_ACCESS_TOKEN:
        required: true

jobs:
  release:
    name: Release CLI
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Download darwin-x86_64 artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}-x86_64-apple-darwin
          path: cli/npm/x86_64-apple-darwin

      - name: Download darwin-aarch64 artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}-aarch64-apple-darwin
          path: cli/npm/aarch64-apple-darwin

      - name: Download linux artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}-linux
          path: cli/npm/x86_64-unknown-linux-musl

      - name: Download windows artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}-windows
          path: cli/npm/x86_64-pc-windows-msvc

      - name: Process artifacts
        shell: bash
        working-directory: cli/npm
        run: |
          mkdir github
          cp aarch64-apple-darwin/grafbase github/grafbase-aarch64-apple-darwin
          cp x86_64-apple-darwin/grafbase github/grafbase-x86_64-apple-darwin
          cp x86_64-pc-windows-msvc/grafbase.exe github/grafbase-x86_64-pc-windows-msvc.exe
          cp x86_64-unknown-linux-musl/grafbase github/grafbase-x86_64-unknown-linux-musl

          chmod +x aarch64-apple-darwin/grafbase
          chmod +x x86_64-apple-darwin/grafbase
          chmod +x x86_64-unknown-linux-musl/grafbase

      - name: Install cargo-binstall and cargo-about
        shell: bash
        run: |
          curl -LsSf https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
          cargo binstall --no-symlinks --no-confirm cargo-about

      - name: Generate licenses
        shell: bash
        run: |
          (cd cli && cargo about generate -o "licenses.html" about.hbs)
          find cli/crates -maxdepth 1 -type d -exec cp cli/licenses.html {} \;
          find cli/npm -maxdepth 1 -type d -exec cp cli/licenses.html {} \;

      - name: Publish cargo
        shell: bash
        working-directory: cli/crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_ACCESS_TOKEN }}
        run: |
          set -e
          set -o pipefail

          retryable() {
            for i in {1..5}; do
              $1 && break || echo 'Retrying in 5...'
              sleep 5
            done

            if [ "$i" -ge 5 ]; then
              echo "Failed to run $1"
              exit 1
            fi
          }

          (cd common && retryable 'cargo publish --allow-dirty')
          (cd server && retryable 'cargo publish --allow-dirty')
          (cd backend && retryable 'cargo publish --allow-dirty')
          (cd cli && retryable 'cargo publish --allow-dirty')

      - name: Publish npm
        shell: bash
        working-directory: cli/npm
        run: |
          npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_ACCESS_TOKEN }}
          (cd aarch64-apple-darwin && npm publish)
          (cd x86_64-apple-darwin && npm publish)
          (cd x86_64-pc-windows-msvc && npm publish)
          (cd x86_64-unknown-linux-musl && npm publish)
          (cd cli && npm publish)

      - name: Github Release
        id: gh-release
        uses: softprops/action-gh-release@v1
        with:
          body_path: cli/changelog/${{ inputs.tag }}.md
          draft: ${{ inputs.draft }}
          files: |
            cli/licenses.html
            cli/npm/github/grafbase-aarch64-apple-darwin
            cli/npm/github/grafbase-x86_64-apple-darwin
            cli/npm/github/grafbase-x86_64-pc-windows-msvc.exe
            cli/npm/github/grafbase-x86_64-unknown-linux-musl
